# Generated by Django 4.2.11 on 2025-03-26 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(default='Texto por defecto')),
                ('Publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='foro_app.publicacion')),
                ('receptor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ayudas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ayudas_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
