# Generated by Django 4.2.11 on 2025-03-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='Publicacion',
        ),
    ]
