# Generated by Django 4.2.11 on 2025-03-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro_app', '0001_initial'),
        ('chat_app', '0002_remove_chat_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='foro_app.publicacion'),
        ),
    ]
